name: TypeDoc to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: |
          yarn install --immutable
          yarn typedoc ./src/index.ts

      - uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: docs
